# **(TRANSFORM DATA PROCESS)**

## Objectives


* Clean `raw_data/insurance.csv`, manage missing values, encode categorical variables, and engineer useful features for analysis.


## Inputs


* raw_data/insurance.csv


## Outputs


* `Insurance_Cleaned_Data.csv` with cleaned, encoded, and feature-engineered data.


## Additional Comments


* This notebook prepares the dataset for exploratory analysis and predictive modelling.

---

# Change working directory

We need to make sure the project root is the active working directory before loading the dataset.

In [1]:
import os
current_dir = os.getcwd()
if os.path.basename(current_dir) == "jupyter_notebooks":
    os.chdir(os.path.dirname(current_dir))
print(f"Current working directory: {os.getcwd()}")

Current working directory: c:\Users\amissetu\Documents\GitHub\Unit_2_ Summative_ Assessment\Unit-_2-_Summative-_Assessment-_Project

# Load the raw dataset

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("raw_data/insurance.csv")
print(f"Rows: {df.shape[0]} | Columns: {df.shape[1]}")
df.head()

Rows: 1338 | Columns: 7

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Review data quality and missing values

In [3]:
print(df.info())
print("\nMissing values per column:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None

Missing values per column:
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

Duplicate rows: 1

# Clean the dataset

In [4]:
df = df.copy()

# Standardise column names and trim whitespace
df.columns = [col.strip().lower() for col in df.columns]

# Remove duplicate records
df = df.drop_duplicates().reset_index(drop=True)

# Fill missing values in a way that preserves data integrity
numeric_cols = df.select_dtypes(include=[np.number]).columns
categorical_cols = df.select_dtypes(include=[object]).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

for col in categorical_cols:
    mode_value = df[col].mode()
    if not mode_value.empty:
        df[col] = df[col].fillna(mode_value.iloc[0])
    else:
        df[col] = df[col].fillna("Unknown")

# Normalise string categories
for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Create new features

In [5]:
# BMI categories based on standard medical thresholds
bins = [0, 18.5, 25, 30, np.inf]
labels = ["underweight", "normal", "overweight", "obese"]
df["bmi_category"] = pd.cut(df["bmi"], bins=bins, labels=labels, right=False)

# Additional feature to capture upper BMI risk
df["bmi_squared"] = df["bmi"] ** 2

df[["bmi", "bmi_category", "bmi_squared", "smoker"]].head()

      bmi bmi_category  bmi_squared smoker
0  27.900   overweight   778.410000    yes
1  33.770        obese  1140.412900     no
2  33.000        obese  1089.000000     no
3  22.705       normal   515.517025     no
4  28.880   overweight   834.054400     no

# Encode categorical variables

In [6]:
encoded_df = pd.get_dummies(df, columns=["sex", "smoker", "region", "bmi_category"], drop_first=False)
dummy_columns = [col for col in encoded_df.columns if col.startswith(("sex_", "smoker_", "region_", "bmi_category_"))]
encoded_df[dummy_columns] = encoded_df[dummy_columns].astype(int)
encoded_df.head()

,age,bmi,children,charges,bmi_squared,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest,bmi_category_underweight,bmi_category_normal,bmi_category_overweight,bmi_category_obese
0,19,27.900,0,16884.92400,778.410000,1,0,0,1,0,0,0,1,0,0,1,0
1,18,33.770,1,1725.55230,1140.412900,0,1,1,0,0,0,1,0,0,0,0,1
2,28,33.000,3,4449.46200,1089.000000,0,1,1,0,0,0,1,0,0,0,0,1
3,33,22.705,0,21984.47061,515.517025,0,1,1,0,0,1,0,0,0,1,0,0
4,32,28.880,0,3866.85520,834.054400,0,1,1,0,0,1,0,0,0,0,1,0

# Save the cleaned dataset

In [7]:
encoded_df.to_csv("Insurance_Cleaned_Data.csv", index=False)
print(f"Saved cleaned dataset with shape: {encoded_df.shape}")
print("\nColumns in cleaned dataset:")
print(encoded_df.columns.tolist())

Saved cleaned dataset with shape: (1337, 17)

Columns in cleaned dataset:
['age', 'bmi', 'children', 'charges', 'bmi_squared', 'sex_female', 'sex_male', 'smoker_no', 'smoker_yes', 'region_northeast', 'region_northwest', 'region_southeast', 'region_southwest', 'bmi_category_underweight', 'bmi_category_normal', 'bmi_category_overweight', 'bmi_category_obese']

---

* Final cleaned dataset is ready for analysis and model development.